version: "3.7"
services:
  app:
      build:
        args:
          user: ahfasxp
          uid: 1000
        context: ./
        dockerfile: Dockerfile
      image: sifut-php
      container_name: sifut-app
      restart: unless-stopped
      working_dir: /var/www/
      volumes:
        - ./:/var/www
      networks:
        - sifut

  db:
    image: mysql:5.7
    container_name: sifut-db
    environment:
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_USER=${DB_USERNAME}
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
      - MYSQL_PASSWORD=${DB_PASSWORD}
    volumes:
      - ./docker/mysql:/var/lib/mysql
    networks:
      - sifut
    
  nginx:
    image: nginx:latest
    container_name: sifut-nginx
    ports:
      - 8000:80
    volumes:
      - ./:/var/www
      - ./docker/nginx:/etc/nginx/conf.d
    networks:
      - sifut

networks:
  sifut:
    driver: bridge